# Generated by Django 5.1.7 on 2025-05-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_pelicula_categorias'),
        ('series', '0002_serie_categorias'),
        ('users', '0003_alter_user_options_user_watched_movies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedepisode',
            options={'verbose_name': 'Episodio visto', 'verbose_name_plural': 'Episodios vistos'},
        ),
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'verbose_name': 'Película vista', 'verbose_name_plural': 'Películas vistas'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched_episodes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched_movies',
        ),
        migrations.AlterField(
            model_name='watchedepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='series.episodio'),
        ),
        migrations.AlterField(
            model_name='watchedepisode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='movies.pelicula'),
        ),
        migrations.AlterField(
            model_name='watchedmovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
