# Generated by Django 5.1.7 on 2025-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
