version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://admin:secret_password@db:5432/bd
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"  # Solo si tu app expone algún puerto

volumes:
  postgres_data:
  redis_data:

