version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
