version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bd # You can change the name of the database if you want
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password # IMPORTANT Change your password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

