# Generated by Django 5.1.7 on 2025-03-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('temporadas', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='series/')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('temporada', models.IntegerField()),
                ('numero', models.IntegerField(help_text='Número de episodio')),
                ('descripcion', models.TextField()),
                ('video', models.FileField(upload_to='episodios/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='episodios/')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='series.serie')),
            ],
            options={
                'verbose_name': 'Episodio',
                'verbose_name_plural': 'Episodios',
                'ordering': ['temporada', 'numero'],
            },
        ),
    ]
