# Generated by Django 5.1.7 on 2025-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinecloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('video', models.FileField(upload_to='peliculas/')),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('categorias', models.ManyToManyField(blank=True, to='cinecloud.categoria')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
